name=LaskakitEpaper
version=0.1.0
author=Patrik Novak
mantainer=Patrik Novak
sentence=Unified interface for e-paper panels.
paragraph=Supports e-paper panels available on LaskaKit.
category=Display
url=https://github.com/LaskaKit/laskakit_epaper
architectures=*
includes=laskakit_epaper.hpp
